adityabisoi/json-hub

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> add contributing.md and codeofconduct.md

- ,github/pull_request_template.md
> create pr template

- feature_request_template.md
> Feature request template added

- .github/ISSUE_TEMPLATE/bug_report.md
issue #2 
Add issue template: bug report
> Fixed issue #2, Add issue template: bug report

- src/api/routes/users.ts
Fixes #19 
POST and DELETE methods removed
> POST and DELETE methods removed

- README.md
> Contributor

- README.md
> Added Tech stack

- src/api/routes/tasks.ts
- src/app.ts
- src/taskdata.json
Issue #24 
- Add /task endpoint
- Add placeholder data in a json file
> Fixed Issue #24, Add a /tasks endpoint

- data/photodata.json
- src/api/routes/photos.ts
- src/app.ts
> added photos endpoint

- src/api/routes/users.ts
> added users delete endpoint

- src/api/routes/users.ts
- closes #1 
- added `PATCH` route in `users.ts`
> added PATCH req in users route

- src/api/routes/home.ts
> fixed Cannot find module 'views/data.js'

- data/animaldata.json
- src/api/routes/animals.ts
- src/app.ts
- closes #78 
- Added `animaldata.json` in `data` folder
- Added `animals.ts` in `route` folder
- Updated `app.ts` with animal route
> Added animals route with data

- src/api/routes/animals.ts
- src/api/routes/vehicles.ts
-   closes #84 
-   added `/animal/type?option=breed`
-   added `/animal/type?option=picture`
-   [x] Tests
> added breed and picture

- src/api/routes/vehicles.ts
-   closes #85 
-  Added endpoint `/vehicles/index` in **vehicles.ts**
-  Added endpoint `/vehicles?manufacturer=Tesla` in **vehicles.ts**
-   [x] Tests
> Added extended endpoint for vehicles

- .editorconfig
- README.md
#66
-   closes #66 
- add editor config
- update readme to install editor config plugin
> add editorconfig, close issue #66

- _test_/users.test.js
- package.json
fixes #39 . Modified the code and unit tests added
> added tests

- src/api/routes/animals.ts
- src/api/routes/photos.ts
> added fetch by id and group endpints in /photos

- src/api/routes/animals.ts
- src/views/data.ts
- src/views/index.ejs
> Updated homepage with new routes

- data/addressdata.json
- src/api/routes/address.ts
- src/app.ts
> Added address endpoint

- data/songdata.json
- src/api/routes/songs.ts
- src/app.ts
-   closes #96 
-   [x] Tests
-   [x] Lint checking 
-   [x] Documentation
> added songdata.json and song route

- src/views/data.ts
-   closes #107 
-   [x] Tests
-   [x] Run Eslint
> added address and song endpoint data to homepage

- data/showsdata.json
- src/api/routes/shows.ts
- src/app.ts
-   closes #109 
-   [x] Tests
> Added shows route

- data/bookdata.json
- src/api/routes/books.ts
- src/app.ts
-   closes #110 
-   [x] Tests
-   [x] Run eslint
> Added books route

- src/app.ts
- src/views/data.ts
-   closes #113 
Added following routes in the `data.ts`
-   [x] Tests
> Updated homepage data

- src/api/routes/books.ts
- src/api/routes/songs.ts
- src/views/data.ts
-   closes #115 
-   [x] Tests
-   [x] Documentation
> added endpoints to books

- src/api/routes/shows.ts
-   closes #116 
-   [x] Tests
> Extended endpoints

- src/api/routes/shows.ts
- src/views/data.ts
-   closes #119 
-   [x] Tests
> updated routes endpoint data

- data/productdata.json
- src/api/routes/products.ts
- src/app.ts
-   closes #122 
-   [x] Tests
-   [x] Documentation
> added product route

- data/moviedata.json
- src/api/routes/movies.ts
- src/app.ts
- src/views/data.ts
-   closes #121 
-   [x] Tests
> Added movie route

- data/sports/cricketdata.json
- src/api/routes/sports.ts
- src/app.ts
-   closes #126  
-   [x] Tests
> Added sports/cricket route

- data/fakedata.json
- src/api/models/user.ts
- src/api/routes/shows.ts
- src/api/routes/users.ts
- src/api/routes/usertest.ts
-   closes #127
- **Schema** `models/user.ts`
- **Routes**
-   [x] Tests
-   [x] Documentation
> Extended user info

- README.md
> installation steps added

- README.md
> documentation on running eslint scripts

- src/server.ts
change default backend port
-   closes #157
> change default backend port

- frontend/src/Routes.js
routes link added 
closes issue #155
> links of routes added

- frontend/src/Main.js
- frontend/src/Route.js
changed routes to route
-   closes #160
> changed routes to route

- frontend/_test_/contact.test.js
- frontend/package.json
- frontend/src/Contact.js
> added tests for contact component

- frontend/_test_/home.test.js
- frontend/package.json
- frontend/src/Home.js
> added tests for home component

- src/_test_/tasks.test.js
> added tests for tasks endpoint

- src/_test_/photos.test.js
> added tests for photos endpoint

- src/_test_/products.test.js
> added tests for product endpoint

- frontend/_test_/vehicles.test.js
added tests for vehicles endpoint
-   closes #154
> added tests for vehicles endpoint

- src/views/index.ejs
-   closes #185 
-   endpoints in photos are now clickable
-   any additional information or context
-   [ ] Tests
-   [ ] Translations
-   [ ] Documentation
|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| 
|
|
> Made photos endpoints clickable
